version: "3.9"
services:
  db:
    image: postgres:15
    container_name: booking_db
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: booking_redis

  booking:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: booking_app
    depends_on:
      - db
      - redis
    command: ./docker/app.sh
    ports:
      - "5000:8000"

  celery:
    build:
      context: .
    container_name: celery
    depends_on:
      - redis
    env_file:
      - .env-non-dev
    command: ./docker/celery.sh
